stages:
  - deploy

deploying:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  when: always
  script:
    - ssh -o "StrictHostKeyChecking=no" root@92.63.99.149 "cd $SITE_DIR && git pull origin master"
