stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make sshpass openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - sshpass -V
    - export SSHPASS=SSH_PASS
    - sshpass -e ssh -o stricthostkeychecking=no root@$HOST ls -la
  when: manual
