image: ubuntu

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

deploying:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no root@"$HOST" cd $SITE_DIR
    - ssh -o StrictHostKeyChecking=no root@"$HOST" git pull origin master
    - ssh -o StrictHostKeyChecking=no root@"$HOST" /opt/php74/bin/php artisan migrate
    - ssh -o StrictHostKeyChecking=no root@"$HOST" yarn prod
    - ssh -o StrictHostKeyChecking=no root@"$HOST" cd .. && chown -R $SITE_USER:$SITE_USER cabinet/* && chown -R $SITE_USER:$SITE_USER cabinet/.*
