image: ubuntu

stages:
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - ssh-keyscan $HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploying:
  stage: deploy
  when: manual
  script:
    - ssh -o StrictHostKeyChecking=no root@"$HOST" ls
    - exit
